if (!require(shiny)) {install.packages("shiny")};  library(shiny)
if (!require(devtools)) {install.packages("devtools")};  library(devtools)
if (!require(ggplot2)) {install.packages("ggplot2")};  library(ggplot2)
if (!require(dplyr)) {install.packages("dplyr")};  library(dplyr)
if (!require(scales)) {install.packages("scales")};  library(scales)
if (!require(grid)) {install.packages("grid")};  library(grid)
if (!require(cluster)) {install.packages("cluster")};  library(cluster)
if (!require(mclust)) {install.packages("mclust")};  library(mclust)
if (!require(MASS)) {install.packages("MASS")};  library(MASS)
if (!require(ggbiplot)) {install_github("vqv/ggbiplot")};  library(ggbiplot)
if (!require(gridExtra)) {install.packages("gridExtra")};  library(gridExtra)
if (!require(dplyr)) {install.packages("dplyr")};  library(dplyr)
# (!require(kableExtra)) {install.packages("kableExtra")};  library(kableExtra)
if (!require(DT)) {install.packages("DT")};  library(DT)
if (!require(dendextend)) {install.packages("dendextend")};  library(dendextend)

